/// Generated by AssetsRefGenerator on 2022/05/25
class Res {
  static const String ar = "assets/lang/ar.json";
  static const String bg = "assets/images/bg.png";
  static const String colors = "assets/json/colors.json";
  static const String en = "assets/lang/en.json";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoWhite = "assets/images/logoWhite.png";
}
