/// Generated by AssetsRefGenerator on 2022/04/22
class Res {
  static const String ar = "assets/lang/ar.json";
  static const String bg = "assets/images/bg.png";
  static const String en = "assets/lang/en.json";
  static const String filter = "assets/images/filter.png";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoWhite = "assets/images/logoWhite.png";
  static const String nodata = "assets/images/nodata.png";
  static const String placeholder = "assets/images/placeholder.png";
  static const String plus = "assets/images/plus.png";
  static const String splash = "assets/images/splash.png";
}
